// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maxcgflfxnezexgbnyvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1heGNnZmxmeG5lemV4Z2JueXZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MDMwNTMsImV4cCI6MjA2NzE3OTA1M30.m-2Esf1VEyJqWycyt3yiy4YmkRn4jUdI8M3trLUhKlw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});